MODEL:
  PRETRAINED: True
 
INPUT:
  SIZE_TRAIN: [224, 224]
  SIZE_TEST: [224, 224]
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing 
  PADDING: 0

DATASETS:
  NAMES: 'uadetrac_reid'
  DATA_PATH: '/home/mond/s/ssd/datasets/UA-DETRAC_ReID'
  TRAIN_PATH: 'image_train'
  QUERY_PATH: 'image_query'
  GALLERY_PATH: 'image_test'

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 32
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 100
  BASE_LR: 0.0003
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64
  FP16: True

  STEPS: [10, 20, 30, 50, 80]
  GAMMA: 0.6

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 8
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 200  # Number of batches between logs.
  EVAL_PERIOD: 10

  CYTHON: True

TEST:
  IMS_PER_BATCH: 64
  DEBUG: True
  WEIGHT: "./outputs/UA-DETRAC_ReID/resnet50_epoch100.pth"

OUTPUT_DIR: "./outputs/UA-DETRAC_ReID"
